# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'test' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for test
  pod 'VersionControl', :git => 'https://gitlab.dtibcn.cat/osam_ios/control_versions_ios.git', :tag => '2.2'

end
